"""
    fixture_privkey() -> Vector{UInt8}

Generate a deterministic 2305-byte private key fixture using the formula:
`byte[i] = UInt8((i * 73 + 19) % 256)` for `i` in `0:(FALCON1024_PRIVKEY_BYTES-1)`.

This matches the reference fixture used in the original QTV research tests.
"""
function fixture_privkey() :: Vector{UInt8}
    return UInt8[UInt8(mod(i * 73 + 19, 256)) for i in 0:(FALCON1024_PRIVKEY_BYTES - 1)]
end

"""
    make_parity_fixture(privkey::Vector{UInt8}, seed::UInt64, swap_sequence::Vector{Int}) -> NamedTuple

Build a QTV from `privkey` and `seed`, apply the given `swap_sequence` (a vector
of target slots), and return a NamedTuple suitable for C++ parity testing.

Fields in the returned NamedTuple:
- `seed`               — UInt64 seed used
- `epoch`              — number of swaps performed
- `initial_permutation`— permutation vector before any swaps
- `final_permutation`  — permutation vector after all swaps
- `bucket_tags`        — SHA-512 hex tags for all 4 buckets
- `working_vector_hex` — hex encoding of the final working vector
- `swap_log`           — vector of swap event records
"""
function make_parity_fixture(
    privkey        :: Vector{UInt8},
    seed           :: UInt64,
    swap_sequence  :: Vector{Int},
) :: NamedTuple
    qtv = build_qtv(privkey; seed=seed, epoch=0)
    initial_perm = copy(qtv.permutation)

    for target in swap_sequence
        swap_active_bucket!(qtv; target_slot=target)
    end

    return (
        seed                = seed,
        epoch               = qtv.epoch,
        initial_permutation = initial_perm,
        final_permutation   = copy(qtv.permutation),
        bucket_tags         = [b.tag for b in qtv.buckets],
        working_vector_hex  = bytes2hex(qtv.working_vector),
        swap_log            = [
            (
                epoch       = ev.epoch,
                from_bucket = ev.from_bucket,
                to_bucket   = ev.to_bucket,
                slot        = ev.slot,
                permutation = collect(ev.permutation),
            ) for ev in qtv.swap_log
        ],
    )
end

"""
    print_cpp_fixture(io::IO, fixture::NamedTuple)

Print `fixture` (produced by `make_parity_fixture`) as C++ initializer code
suitable for pasting into test files under `src/LLP/tests/`.
"""
function print_cpp_fixture(io::IO, fixture::NamedTuple)
    println(io, "// LLLTaoQTV parity fixture — generated by Julia LLLTaoQTV.parity")
    println(io, "// Paste into src/LLP/tests/ C++ test files for round-trip validation")
    println(io, "")
    println(io, "static const uint64_t FIXTURE_SEED  = 0x$(string(fixture.seed, base=16, pad=16));")
    println(io, "static const int      FIXTURE_EPOCH = $(fixture.epoch);")
    println(io, "")
    # Initial permutation
    perm_str = join(fixture.initial_permutation .- 1, ", ")   # convert to 0-based for C++
    println(io, "static const int FIXTURE_INITIAL_PERM[] = { $perm_str };")
    perm_str = join(fixture.final_permutation .- 1, ", ")
    println(io, "static const int FIXTURE_FINAL_PERM[]   = { $perm_str };")
    println(io, "")
    println(io, "// Working vector (hex) after $(fixture.epoch) swap(s):")
    println(io, "static const char FIXTURE_WORKING_VECTOR_HEX[] =")
    println(io, "    \"$(fixture.working_vector_hex)\";")
    println(io, "")
    println(io, "// Bucket SHA-512 tags:")
    for (i, tag) in enumerate(fixture.bucket_tags)
        println(io, "static const char FIXTURE_BUCKET$(i)_TAG[] =")
        println(io, "    \"$tag\";")
    end
    println(io, "")
    println(io, "// Swap log ($(length(fixture.swap_log)) event(s)):")
    for ev in fixture.swap_log
        perm_str = join(ev.permutation .- 1, ", ")
        println(io, "// epoch=$(ev.epoch): bucket $(ev.from_bucket-1) -> $(ev.to_bucket-1) slot=$(ev.slot-1) perm=[$perm_str]")
    end
end
