#!/bin/tcsh
#
# RL - Restart LISP Wrapper Script
#
# Nexus/LISP wrapper script to start the lispers.net LISP subsystem.
# This script makes two calls. One to a provisioning program that will
# provision the lisp.config and setup kernel routes in the routing table.
# And the other to start the lispers.net LISP subsystem.
#
# This script is used by either a client or seed nexus/lisp node. And can be
# run inside a docker container or natively on most unix derived OS platforms.
#
# The lispers.net code does not run natively on Windows. You must install
# docker on the platform to run it.
#
#------------------------------------------------------------------------------

#
# Default to docker default device of eth0. If you are running natively, you
# pick your interface where your default route points to. Run the following
# to find out: "ip route | egrep default".
#
set device = "eth0"

#
# If caller does a "setenv EID4 <ipv4-eid>" and "setenv EID6 <ipv6-eid>", the
# EID values will be passed to provision-lisp.py to provision the lisp.config
# file with the supplied EIDs. Otherwise, random values will be created.
#
if($?EID4 == 0) then
    set EID4 = ""
endif
if($?EID6 == 0) then
    set EID6 = ""
endif

#
# Go into directory where RL resides.
#
cd `dirname $0`

#
# Provision lisp.config and/or reinstall kernel routes.
#
python provision-lisp.py $device $EID4 $EID6

#
# Start the lispers.net LISP subsystem, quietly.
#
/lispers.net/RESTART-LISP -9090 $device > /dev/null
exit
