#!/bin/tcsh
#
# RL - Restart LISP Wrapper Script
#
# Nexus/LISP wrapper script to start the lispers.net LISP subsystem.
# This script makes two calls. One to a provisioning program that will
# provision the lisp.config and setup kernel routes in the routing table.
# And the other to start the lispers.net LISP subsystem.
#
# This script is used by either a client or seed nexus/lisp node. And can be
# run inside a docker container or natively on most unix derived OS platforms.
#
# The lispers.net code does not run natively on Windows. You must install
# docker on the platform to run it.
#
#------------------------------------------------------------------------------

#
# Default to docker default device of eth0. If you are running natively, you
# pick your interface where your default route points to. Run the following
# to find out: "ip route | egrep default".
#
set device = "eth0"

#
# Go into directory where RL resides.
#
cd `dirname $0`

#
# Provision lisp.config and/or reinstall kernel routes. If you want to pass
# in EIDs for a seed node, use the second form of the command below.
#
python provision-lisp.py $device
#python provision-lisp.py $device <ipv4-eid> <ipv6-eid>

#
# Start the lispers.net LISP subsystem, quietly.
#
/lispers.net/RESTART-LISP -9090 $device > /dev/null
exit
