#!/bin/sh
#
# docker-run-tritium
#
# This script is used on your host OS to create and start a docker container
# that runs the Nexus Daemon and the lispers.net LISP subsystem for a client
# (non-seed) node..
#
# You can run this script multiple times and it will create as many containers
# as you wish. The docker image "tritium" must already be built by using
# "docker build".
#
# Note the port number allocated to get to the lispers.net webpage interface
# can be found in the PORTS column of "docker ps".
#
# Usage: docker-run-tritium [<ipv4-eid> <ipv6-eid> <container-name>]
#
HOSTNAME=`hostname | cut -d "." -f 1`
RAND=`python -c "import random as r; print hex(r.randint(0, 0xffffffff))[2::]"`
if [ -z "$3" ] ; then
    NAME="nexus-$HOSTNAME-$RAND"
else    
    NAME="$3"
fi

#
# When one container is running, we use port 9090 for accessing the lispers.net
# restful API. If a user wants to run multiple containers, then use a random
#
CONTAINER=`docker ps | egrep nexus-$HOSTNAME | egrep 9090`
if [ -z "$CONTAINER" ] ; then
    LPORT="9090"
    NPORT="8080"
    MPORT="9336"
    TPORT="8336"
else
    LPORT=""
    NPORT=""
    MPORT=""
    TPORT=""
fi

#
# Create container.
#
#docker create -p $NPORT:8080 -p $LPORT:9090 -p $MPORT:9336 -p $TPORT:8336 \
#    --privileged --name $NAME -h $NAME -ti tritium > /dev/null

docker create -p $NPORT:8080 -p $LPORT:9090 -v /:/hostOS -e "EID4=$1" \
       -e "EID6=$2" -e "NAME=$NAME" --privileged --name $NAME -h $NAME \
       -ti tritium > /dev/null

#
# Startup container.
#
echo "Starting container '$NAME' ..."
docker start $NAME > /dev/null
