#!/bin/bash
#
# nexus-save-data
#
# Usage: nexus-save-datadir <hostOS-location>
#

DEST="/hostOS$HOSTOS_HOME/.Nexus_Core_Data_BETA"
if [ ! -d $DEST ] ; then
   echo "Nexus data directory $DEST does not exist"
   exit 
fi   

#
# debug.log could be enourmous, don't copy it. If you want it comment out line
# below.
#
rm -f /root/.Nexus/debug.log

#
# Do the copy.
#
echo -n "Copying /root/.Nexus -> $DEST ... "
cp -r /root/.Nexus/* $DEST
echo "done"


