var namespace_legacy =
[
    [ "Account", "class_legacy_1_1_account.html", "class_legacy_1_1_account" ],
    [ "AccountingEntry", "class_legacy_1_1_accounting_entry.html", "class_legacy_1_1_accounting_entry" ],
    [ "AddressBook", "class_legacy_1_1_address_book.html", "class_legacy_1_1_address_book" ],
    [ "BasicKeyStore", "class_legacy_1_1_basic_key_store.html", "class_legacy_1_1_basic_key_store" ],
    [ "BerkeleyDB", "class_legacy_1_1_berkeley_d_b.html", "class_legacy_1_1_berkeley_d_b" ],
    [ "Crypter", "class_legacy_1_1_crypter.html", "class_legacy_1_1_crypter" ],
    [ "CryptoKeyStore", "class_legacy_1_1_crypto_key_store.html", "class_legacy_1_1_crypto_key_store" ],
    [ "FLAGS", "struct_legacy_1_1_f_l_a_g_s.html", "struct_legacy_1_1_f_l_a_g_s" ],
    [ "InPoint", "class_legacy_1_1_in_point.html", "class_legacy_1_1_in_point" ],
    [ "KeyPool", "class_legacy_1_1_key_pool.html", "class_legacy_1_1_key_pool" ],
    [ "KeyPoolEntry", "class_legacy_1_1_key_pool_entry.html", "class_legacy_1_1_key_pool_entry" ],
    [ "KeyStore", "class_legacy_1_1_key_store.html", "class_legacy_1_1_key_store" ],
    [ "LegacyBlock", "class_legacy_1_1_legacy_block.html", "class_legacy_1_1_legacy_block" ],
    [ "Locator", "class_legacy_1_1_locator.html", "class_legacy_1_1_locator" ],
    [ "MasterKey", "class_legacy_1_1_master_key.html", "class_legacy_1_1_master_key" ],
    [ "MerkleTx", "class_legacy_1_1_merkle_tx.html", "class_legacy_1_1_merkle_tx" ],
    [ "NexusAddress", "class_legacy_1_1_nexus_address.html", "class_legacy_1_1_nexus_address" ],
    [ "NexusSecret", "class_legacy_1_1_nexus_secret.html", "class_legacy_1_1_nexus_secret" ],
    [ "OutPoint", "class_legacy_1_1_out_point.html", "class_legacy_1_1_out_point" ],
    [ "Output", "class_legacy_1_1_output.html", "class_legacy_1_1_output" ],
    [ "ReserveKey", "class_legacy_1_1_reserve_key.html", "class_legacy_1_1_reserve_key" ],
    [ "Script", "class_legacy_1_1_script.html", "class_legacy_1_1_script" ],
    [ "StakeMinter", "class_legacy_1_1_stake_minter.html", "class_legacy_1_1_stake_minter" ],
    [ "Transaction", "class_legacy_1_1_transaction.html", "class_legacy_1_1_transaction" ],
    [ "TxIn", "class_legacy_1_1_tx_in.html", "class_legacy_1_1_tx_in" ],
    [ "TxOut", "class_legacy_1_1_tx_out.html", "class_legacy_1_1_tx_out" ],
    [ "Wallet", "class_legacy_1_1_wallet.html", "class_legacy_1_1_wallet" ],
    [ "WalletDB", "class_legacy_1_1_wallet_d_b.html", "class_legacy_1_1_wallet_d_b" ],
    [ "WalletKey", "class_legacy_1_1_wallet_key.html", "class_legacy_1_1_wallet_key" ],
    [ "WalletTx", "class_legacy_1_1_wallet_tx.html", "class_legacy_1_1_wallet_tx" ]
];