var namespacejson_1_1detail =
[
    [ "dtoa_impl", "namespacejson_1_1detail_1_1dtoa__impl.html", "namespacejson_1_1detail_1_1dtoa__impl" ],
    [ "binary_reader", "classjson_1_1detail_1_1binary__reader.html", "classjson_1_1detail_1_1binary__reader" ],
    [ "binary_writer", "classjson_1_1detail_1_1binary__writer.html", "classjson_1_1detail_1_1binary__writer" ],
    [ "detector", "structjson_1_1detail_1_1detector.html", "structjson_1_1detail_1_1detector" ],
    [ "detector< Default, void_t< Op< Args... > >, Op, Args... >", "structjson_1_1detail_1_1detector_3_01_default_00_01void__t_3_01_op_3_01_args_8_8_8_01_4_01_4_00_01_op_00_01_args_8_8_8_01_4.html", "structjson_1_1detail_1_1detector_3_01_default_00_01void__t_3_01_op_3_01_args_8_8_8_01_4_01_4_00_01_op_00_01_args_8_8_8_01_4" ],
    [ "exception", "classjson_1_1detail_1_1exception.html", "classjson_1_1detail_1_1exception" ],
    [ "external_constructor", "structjson_1_1detail_1_1external__constructor.html", null ],
    [ "external_constructor< value_t::array >", "structjson_1_1detail_1_1external__constructor_3_01value__t_1_1array_01_4.html", null ],
    [ "external_constructor< value_t::boolean >", "structjson_1_1detail_1_1external__constructor_3_01value__t_1_1boolean_01_4.html", null ],
    [ "external_constructor< value_t::number_float >", "structjson_1_1detail_1_1external__constructor_3_01value__t_1_1number__float_01_4.html", null ],
    [ "external_constructor< value_t::number_integer >", "structjson_1_1detail_1_1external__constructor_3_01value__t_1_1number__integer_01_4.html", null ],
    [ "external_constructor< value_t::number_unsigned >", "structjson_1_1detail_1_1external__constructor_3_01value__t_1_1number__unsigned_01_4.html", null ],
    [ "external_constructor< value_t::object >", "structjson_1_1detail_1_1external__constructor_3_01value__t_1_1object_01_4.html", null ],
    [ "external_constructor< value_t::string >", "structjson_1_1detail_1_1external__constructor_3_01value__t_1_1string_01_4.html", null ],
    [ "from_json_fn", "structjson_1_1detail_1_1from__json__fn.html", "structjson_1_1detail_1_1from__json__fn" ],
    [ "has_from_json", "structjson_1_1detail_1_1has__from__json.html", null ],
    [ "has_from_json< BasicJsonType, T, enable_if_t< not is_basic_json< T >::value > >", "structjson_1_1detail_1_1has__from__json_3_01_basic_json_type_00_01_t_00_01enable__if__t_3_01not_021582337a6e36b3082433a6841f9580.html", "structjson_1_1detail_1_1has__from__json_3_01_basic_json_type_00_01_t_00_01enable__if__t_3_01not_021582337a6e36b3082433a6841f9580" ],
    [ "has_non_default_from_json", "structjson_1_1detail_1_1has__non__default__from__json.html", null ],
    [ "has_non_default_from_json< BasicJsonType, T, enable_if_t< not is_basic_json< T >::value > >", "structjson_1_1detail_1_1has__non__default__from__json_3_01_basic_json_type_00_01_t_00_01enable__e8ddb4c7aaaeb7b55c6d49178cd41b74.html", "structjson_1_1detail_1_1has__non__default__from__json_3_01_basic_json_type_00_01_t_00_01enable__e8ddb4c7aaaeb7b55c6d49178cd41b74" ],
    [ "has_to_json", "structjson_1_1detail_1_1has__to__json.html", null ],
    [ "has_to_json< BasicJsonType, T, enable_if_t< not is_basic_json< T >::value > >", "structjson_1_1detail_1_1has__to__json_3_01_basic_json_type_00_01_t_00_01enable__if__t_3_01not_016908c0de89d249807db9ab0f17fde137.html", "structjson_1_1detail_1_1has__to__json_3_01_basic_json_type_00_01_t_00_01enable__if__t_3_01not_016908c0de89d249807db9ab0f17fde137" ],
    [ "index_sequence", "structjson_1_1detail_1_1index__sequence.html", "structjson_1_1detail_1_1index__sequence" ],
    [ "input_adapter", "classjson_1_1detail_1_1input__adapter.html", "classjson_1_1detail_1_1input__adapter" ],
    [ "input_adapter_protocol", "structjson_1_1detail_1_1input__adapter__protocol.html", "structjson_1_1detail_1_1input__adapter__protocol" ],
    [ "input_buffer_adapter", "classjson_1_1detail_1_1input__buffer__adapter.html", "classjson_1_1detail_1_1input__buffer__adapter" ],
    [ "input_stream_adapter", "classjson_1_1detail_1_1input__stream__adapter.html", "classjson_1_1detail_1_1input__stream__adapter" ],
    [ "internal_iterator", "structjson_1_1detail_1_1internal__iterator.html", "structjson_1_1detail_1_1internal__iterator" ],
    [ "invalid_iterator", "classjson_1_1detail_1_1invalid__iterator.html", null ],
    [ "is_basic_json", "structjson_1_1detail_1_1is__basic__json.html", null ],
    [ "is_basic_json< NLOHMANN_BASIC_JSON_TPL >", "structjson_1_1detail_1_1is__basic__json_3_01_n_l_o_h_m_a_n_n___b_a_s_i_c___j_s_o_n___t_p_l_01_4.html", null ],
    [ "is_compatible_array_type", "structjson_1_1detail_1_1is__compatible__array__type.html", null ],
    [ "is_compatible_array_type_impl", "structjson_1_1detail_1_1is__compatible__array__type__impl.html", null ],
    [ "is_compatible_array_type_impl< BasicJsonType, CompatibleArrayType, enable_if_t< is_detected< value_type_t, CompatibleArrayType >::value and is_detected< iterator_t, CompatibleArrayType >::value and not is_iterator_traits< std::iterator_traits< CompatibleArrayType > >::value > >", "structjson_1_1detail_1_1is__compatible__array__type__impl_3_01_basic_json_type_00_01_compatible_89034e5e3d62df6924a0700d09b5718b.html", null ],
    [ "is_compatible_integer_type", "structjson_1_1detail_1_1is__compatible__integer__type.html", null ],
    [ "is_compatible_integer_type_impl", "structjson_1_1detail_1_1is__compatible__integer__type__impl.html", null ],
    [ "is_compatible_integer_type_impl< RealIntegerType, CompatibleNumberIntegerType, enable_if_t< std::is_integral< RealIntegerType >::value and std::is_integral< CompatibleNumberIntegerType >::value and not std::is_same< bool, CompatibleNumberIntegerType >::value > >", "structjson_1_1detail_1_1is__compatible__integer__type__impl_3_01_real_integer_type_00_01_compati908712cd511e2703eba30204e3699a8e.html", "structjson_1_1detail_1_1is__compatible__integer__type__impl_3_01_real_integer_type_00_01_compati908712cd511e2703eba30204e3699a8e" ],
    [ "is_compatible_object_type", "structjson_1_1detail_1_1is__compatible__object__type.html", null ],
    [ "is_compatible_object_type_impl", "structjson_1_1detail_1_1is__compatible__object__type__impl.html", null ],
    [ "is_compatible_object_type_impl< BasicJsonType, CompatibleObjectType, enable_if_t< is_detected< mapped_type_t, CompatibleObjectType >::value and is_detected< key_type_t, CompatibleObjectType >::value > >", "structjson_1_1detail_1_1is__compatible__object__type__impl_3_01_basic_json_type_00_01_compatiblea606632fc5628ac8562c80789692f3a9.html", "structjson_1_1detail_1_1is__compatible__object__type__impl_3_01_basic_json_type_00_01_compatiblea606632fc5628ac8562c80789692f3a9" ],
    [ "is_compatible_string_type", "structjson_1_1detail_1_1is__compatible__string__type.html", null ],
    [ "is_compatible_string_type_impl", "structjson_1_1detail_1_1is__compatible__string__type__impl.html", null ],
    [ "is_compatible_string_type_impl< BasicJsonType, CompatibleStringType, enable_if_t< is_detected_exact< typename BasicJsonType::string_t::value_type, value_type_t, CompatibleStringType >::value > >", "structjson_1_1detail_1_1is__compatible__string__type__impl_3_01_basic_json_type_00_01_compatiblebf4dbf75534cfd04079c59b9f20ed9d9.html", null ],
    [ "is_compatible_type", "structjson_1_1detail_1_1is__compatible__type.html", null ],
    [ "is_compatible_type_impl", "structjson_1_1detail_1_1is__compatible__type__impl.html", null ],
    [ "is_compatible_type_impl< BasicJsonType, CompatibleType, enable_if_t< is_complete_type< CompatibleType >::value > >", "structjson_1_1detail_1_1is__compatible__type__impl_3_01_basic_json_type_00_01_compatible_type_00bcf23bededb990cd7101074248c36079.html", null ],
    [ "is_complete_type", "structjson_1_1detail_1_1is__complete__type.html", null ],
    [ "is_complete_type< T, decltype(void(sizeof(T)))>", "structjson_1_1detail_1_1is__complete__type_3_01_t_00_01decltype_07void_07sizeof_07_t_08_08_08_4.html", null ],
    [ "is_constructible_array_type", "structjson_1_1detail_1_1is__constructible__array__type.html", null ],
    [ "is_constructible_array_type_impl", "structjson_1_1detail_1_1is__constructible__array__type__impl.html", null ],
    [ "is_constructible_array_type_impl< BasicJsonType, ConstructibleArrayType, enable_if_t< not std::is_same< ConstructibleArrayType, typename BasicJsonType::value_type >::value and is_detected< value_type_t, ConstructibleArrayType >::value and is_detected< iterator_t, ConstructibleArrayType >::value and is_complete_type< detected_t< value_type_t, ConstructibleArrayType > >::value > >", "structjson_1_1detail_1_1is__constructible__array__type__impl_3_01_basic_json_type_00_01_construcf9929cb3f105d302ae4157128eafa78d.html", null ],
    [ "is_constructible_array_type_impl< BasicJsonType, ConstructibleArrayType, enable_if_t< std::is_same< ConstructibleArrayType, typename BasicJsonType::value_type >::value > >", "structjson_1_1detail_1_1is__constructible__array__type__impl_3_01_basic_json_type_00_01_construc8a4713abdcc38450c355c05f9556a97c.html", null ],
    [ "is_constructible_object_type", "structjson_1_1detail_1_1is__constructible__object__type.html", null ],
    [ "is_constructible_object_type_impl", "structjson_1_1detail_1_1is__constructible__object__type__impl.html", null ],
    [ "is_constructible_object_type_impl< BasicJsonType, ConstructibleObjectType, enable_if_t< is_detected< mapped_type_t, ConstructibleObjectType >::value and is_detected< key_type_t, ConstructibleObjectType >::value > >", "structjson_1_1detail_1_1is__constructible__object__type__impl_3_01_basic_json_type_00_01_construd64baa9df8ea9fc3e6fbcdb0724980b8.html", "structjson_1_1detail_1_1is__constructible__object__type__impl_3_01_basic_json_type_00_01_construd64baa9df8ea9fc3e6fbcdb0724980b8" ],
    [ "is_constructible_string_type", "structjson_1_1detail_1_1is__constructible__string__type.html", null ],
    [ "is_constructible_string_type_impl", "structjson_1_1detail_1_1is__constructible__string__type__impl.html", null ],
    [ "is_constructible_string_type_impl< BasicJsonType, ConstructibleStringType, enable_if_t< is_detected_exact< typename BasicJsonType::string_t::value_type, value_type_t, ConstructibleStringType >::value > >", "structjson_1_1detail_1_1is__constructible__string__type__impl_3_01_basic_json_type_00_01_constru4cb5e06dd267e48e2d27f6ea5b5ec6a6.html", null ],
    [ "is_iterator_traits", "structjson_1_1detail_1_1is__iterator__traits.html", null ],
    [ "is_iterator_traits< std::iterator_traits< T > >", "structjson_1_1detail_1_1is__iterator__traits_3_01std_1_1iterator__traits_3_01_t_01_4_01_4.html", null ],
    [ "is_sax", "structjson_1_1detail_1_1is__sax.html", null ],
    [ "is_sax_static_asserts", "structjson_1_1detail_1_1is__sax__static__asserts.html", null ],
    [ "iter_impl", "classjson_1_1detail_1_1iter__impl.html", "classjson_1_1detail_1_1iter__impl" ],
    [ "iteration_proxy", "classjson_1_1detail_1_1iteration__proxy.html", "classjson_1_1detail_1_1iteration__proxy" ],
    [ "json_ref", "classjson_1_1detail_1_1json__ref.html", "classjson_1_1detail_1_1json__ref" ],
    [ "json_reverse_iterator", "classjson_1_1detail_1_1json__reverse__iterator.html", "classjson_1_1detail_1_1json__reverse__iterator" ],
    [ "json_sax_acceptor", "classjson_1_1detail_1_1json__sax__acceptor.html", "classjson_1_1detail_1_1json__sax__acceptor" ],
    [ "json_sax_dom_callback_parser", "classjson_1_1detail_1_1json__sax__dom__callback__parser.html", "classjson_1_1detail_1_1json__sax__dom__callback__parser" ],
    [ "json_sax_dom_parser", "classjson_1_1detail_1_1json__sax__dom__parser.html", "classjson_1_1detail_1_1json__sax__dom__parser" ],
    [ "lexer", "classjson_1_1detail_1_1lexer.html", "classjson_1_1detail_1_1lexer" ],
    [ "make_index_sequence", "structjson_1_1detail_1_1make__index__sequence.html", null ],
    [ "make_index_sequence< 0 >", "structjson_1_1detail_1_1make__index__sequence_3_010_01_4.html", null ],
    [ "make_index_sequence< 1 >", "structjson_1_1detail_1_1make__index__sequence_3_011_01_4.html", null ],
    [ "make_void", "structjson_1_1detail_1_1make__void.html", "structjson_1_1detail_1_1make__void" ],
    [ "merge_and_renumber", "structjson_1_1detail_1_1merge__and__renumber.html", null ],
    [ "merge_and_renumber< index_sequence< I1... >, index_sequence< I2... > >", "structjson_1_1detail_1_1merge__and__renumber_3_01index__sequence_3_01_i1_8_8_8_01_4_00_01index__40bedf67c08309271f0e465594b19ea5.html", null ],
    [ "nonesuch", "structjson_1_1detail_1_1nonesuch.html", "structjson_1_1detail_1_1nonesuch" ],
    [ "other_error", "classjson_1_1detail_1_1other__error.html", null ],
    [ "out_of_range", "classjson_1_1detail_1_1out__of__range.html", null ],
    [ "output_adapter", "classjson_1_1detail_1_1output__adapter.html", "classjson_1_1detail_1_1output__adapter" ],
    [ "output_adapter_protocol", "structjson_1_1detail_1_1output__adapter__protocol.html", "structjson_1_1detail_1_1output__adapter__protocol" ],
    [ "output_stream_adapter", "classjson_1_1detail_1_1output__stream__adapter.html", "classjson_1_1detail_1_1output__stream__adapter" ],
    [ "output_string_adapter", "classjson_1_1detail_1_1output__string__adapter.html", "classjson_1_1detail_1_1output__string__adapter" ],
    [ "output_vector_adapter", "classjson_1_1detail_1_1output__vector__adapter.html", "classjson_1_1detail_1_1output__vector__adapter" ],
    [ "parse_error", "classjson_1_1detail_1_1parse__error.html", "classjson_1_1detail_1_1parse__error" ],
    [ "parser", "classjson_1_1detail_1_1parser.html", "classjson_1_1detail_1_1parser" ],
    [ "position_t", "structjson_1_1detail_1_1position__t.html", "structjson_1_1detail_1_1position__t" ],
    [ "primitive_iterator_t", "classjson_1_1detail_1_1primitive__iterator__t.html", "classjson_1_1detail_1_1primitive__iterator__t" ],
    [ "priority_tag", "structjson_1_1detail_1_1priority__tag.html", null ],
    [ "priority_tag< 0 >", "structjson_1_1detail_1_1priority__tag_3_010_01_4.html", null ],
    [ "serializer", "classjson_1_1detail_1_1serializer.html", "classjson_1_1detail_1_1serializer" ],
    [ "static_const", "structjson_1_1detail_1_1static__const.html", null ],
    [ "to_json_fn", "structjson_1_1detail_1_1to__json__fn.html", "structjson_1_1detail_1_1to__json__fn" ],
    [ "type_error", "classjson_1_1detail_1_1type__error.html", null ],
    [ "wide_string_input_adapter", "classjson_1_1detail_1_1wide__string__input__adapter.html", "classjson_1_1detail_1_1wide__string__input__adapter" ],
    [ "wide_string_input_helper", "structjson_1_1detail_1_1wide__string__input__helper.html", null ],
    [ "wide_string_input_helper< WideStringType, 2 >", "structjson_1_1detail_1_1wide__string__input__helper_3_01_wide_string_type_00_012_01_4.html", null ]
];